#!/bin/bash
# Bulk docTruth Configuration Generator
# Author: Chude <chude@emeke.org>
#
# Purpose: Generate .doctruth.yml for all projects that don't have one
# Usage: bash generate-doctruth-configs.sh [--dry-run] [--project PROJECT_NAME]

set -eo pipefail

# Configuration
PROJECTS_DIR="$HOME/Projects"
DRY_RUN=false
SPECIFIC_PROJECT=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        --project)
            SPECIFIC_PROJECT="$2"
            shift 2
            ;;
        --dir)
            PROJECTS_DIR="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--dry-run] [--project PROJECT_NAME] [--dir PROJECTS_DIR]"
            exit 1
            ;;
    esac
done

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "docTruth Bulk Configuration Generator"
echo "======================================"
echo ""
echo "Projects directory: $PROJECTS_DIR"
echo "Dry run: $DRY_RUN"
echo ""

# Check if doctruth is installed
if ! command -v doctruth &>/dev/null; then
    echo -e "${YELLOW}⚠️  doctruth not installed${NC}"
    echo "Install with: npm install -g doctruth"
    exit 1
fi

# Counters
total=0
generated=0
skipped=0
errors=0

# Process each project
while IFS= read -r project_dir; do
    project_name=$(basename "$project_dir")

    # Skip if specific project requested and this isn't it
    if [[ -n "$SPECIFIC_PROJECT" ]] && [[ "$project_name" != "$SPECIFIC_PROJECT" ]]; then
        continue
    fi

    # Skip special directories
    [[ "$project_name" == "tmp" ]] && continue
    [[ "$project_name" == "node_modules" ]] && continue
    [[ "$project_name" == ".claude" ]] && continue
    [[ "$project_name" == ".protected" ]] && continue

    ((total++))

    # Check if already has config
    if [[ -f "$project_dir/.doctruth.yml" ]]; then
        echo -e "${GREEN}✓${NC} $project_name - already configured"
        ((skipped++))
        continue
    fi

    # Detect project type
    preset="generic"
    if [[ -f "$project_dir/package.json" ]]; then
        if grep -q "react" "$project_dir/package.json" 2>/dev/null; then
            preset="nodejs"  # doctruth's nodejs preset handles React
        else
            preset="nodejs"
        fi
    elif [[ -f "$project_dir/setup.py" ]] || [[ -f "$project_dir/pyproject.toml" ]] || [[ -f "$project_dir/requirements.txt" ]]; then
        preset="python"
    else
        # Count shell files
        sh_count=$(find "$project_dir" -maxdepth 2 -name "*.sh" 2>/dev/null | wc -l)
        if [[ $sh_count -gt 5 ]]; then
            preset="bash"
        fi
    fi

    if [[ "$DRY_RUN" == true ]]; then
        echo -e "${BLUE}[DRY RUN]${NC} Would generate: $project_name (preset: $preset)"
        ((generated++))
    else
        echo -e "${YELLOW}→${NC} Generating config for $project_name (preset: $preset)..."

        # Generate config
        (
            cd "$project_dir" || exit 1

            # Use doctruth's built-in preset initialization
            if doctruth --init --preset "$preset" --force 2>&1 | grep -q "initialized"; then
                echo -e "  ${GREEN}✓${NC} Configuration generated"
                ((generated++))
            else
                # Fallback: create basic config manually
                cat > .doctruth.yml <<EOF
# docTruth Configuration for $project_name
# Auto-generated by wow-system bulk generator
# Author: Chude <chude@emeke.org>

version: 1
project: $project_name
output: CURRENT_TRUTH.md

meta:
  description: "$project_name project"
  timeout_seconds: 10
  fail_on_error: false

truth_sources:
  - name: "Project Type"
    command: "echo '$preset'"
    essential: true
    category: "Project"

  - name: "Project Structure"
    command: "find . -maxdepth 2 -type f -not -path '*/node_modules/*' -not -path '*/.git/*' | head -20"
    category: "Structure"

validations: []
working_examples: []
EOF
                echo -e "  ${GREEN}✓${NC} Basic configuration created"
                ((generated++))
            fi
        ) || {
            echo -e "  ${YELLOW}✗${NC} Error generating config"
            ((errors++))
        }
    fi

done < <(find "$PROJECTS_DIR" -maxdepth 1 -type d | sort)

# Summary
echo ""
echo "Summary:"
echo "--------"
echo "Total projects scanned: $total"
echo "Already configured: $skipped"
echo "Newly generated: $generated"
echo "Errors: $errors"

if [[ "$DRY_RUN" == true ]]; then
    echo ""
    echo -e "${BLUE}ℹ️  This was a dry run. Run without --dry-run to actually generate configs.${NC}"
fi

exit 0
